version: 2.1

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

executors:
  node:
    docker:
      - image: circleci/node:latest
    working_directory: ~/react-connected-reducers

jobs:
  lint:
    executor: node
    steps:
      - install
      - run: npm run lint

  test:
    executor: node
    steps:
      - install
      - run: npm test

  build:
    executor: node
    steps:
      - install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish:
    executor: node
    steps:
      - install
      - run: npm publish

workflows:
  version: 2
  lint_test_build_and_publish:
    jobs:
      - lint
      - test
      - build
      - approve:
          type: approval
          requires:
            - lint
            - test
            - build
          filters:
                tags:
                  only: /^v.*/
                # TODO: Enable branch filter before merging.
                # branches:
                #   only: master
      - publish:
          requires:
            - approve
